
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Dec 31 04:46:44 CET 2019
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR = 45;
  public static final int CONST = 7;
  public static final int GE = 24;
  public static final int LPAREN = 36;
  public static final int SEMI = 33;
  public static final int CONTINUE = 16;
  public static final int FOR = 14;
  public static final int RPAREN = 37;
  public static final int AND = 28;
  public static final int OR = 29;
  public static final int BOOL = 42;
  public static final int COMMA = 34;
  public static final int CLASS = 4;
  public static final int INC = 31;
  public static final int DIV = 20;
  public static final int EXT = 15;
  public static final int GEQ = 25;
  public static final int PLUS = 17;
  public static final int ASSIGN = 30;
  public static final int IF = 8;
  public static final int DOT = 35;
  public static final int LE = 26;
  public static final int ABSTRACT = 5;
  public static final int EOF = 0;
  public static final int RETURN = 12;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MUL = 19;
  public static final int NUMBER = 43;
  public static final int MOD = 21;
  public static final int NEQ = 23;
  public static final int IDENT = 44;
  public static final int BREAK = 3;
  public static final int VOID = 13;
  public static final int EQ = 22;
  public static final int LBRACE = 40;
  public static final int ELSE = 6;
  public static final int LSQUARE = 38;
  public static final int READ = 11;
  public static final int RSQUARE = 39;
  public static final int RBRACE = 41;
  public static final int LEQ = 27;
  public static final int DEC = 32;
  public static final int SUB = 18;
  public static final int PRINT = 10;
}

